In [ ]:

# FOR LOOP
# variable 1
for i in range(10):
  print(i)

#variable 2
string="pakistan is my country"
for x in range(3,6):
     print(string[x])

#variable 3
name="zohaib"
for char in name:
   print(char)

#variable 4
for num in range(50,6, -3):
    print(num)

#variable 5
for z in range(20,39):
    if (z%2==0):
      print(z," is even number")

#variable 6
tpl=("pakistan", "india", "china")
for country in tpl:
    print(country)

#variable 7
student="sardar zohaib dogar"
count =0
for char in student:
     count +=1
print("number of characters: ", count)

#variable 8
uni="islamia university of bahawalpur"
letter="y"
for f in range (len(uni)):
     if uni[f]==letter:
       print(" indedx of letter is: ",f)

#variable 9
for _ in range(10):
   print("bhar main jao")

#variable 10
for p in range(50,6700):
   if p*p<=6700:
    print (p ," is a number whose square is between 50 and 6700")

0
1
2
3
4
5
6
7
8
9
i
s
t
z
o
h
a
i
b
50
47
44
41
38
35
32
29
26
23
20
17
14
11
8
20  is even number
22  is even number
24  is even number
26  is even number
28  is even number
30  is even number
32  is even number
34  is even number
36  is even number
38  is even number
pakistan
india
china
number of characters:  19
 indedx of letter is:  17
bhar main jao
bhar main jao
bhar main jao
bhar main jao
bhar main jao
bhar main jao
bhar main jao
bhar main jao
bhar main jao
bhar main jao
50  is a number whose square is between 50 and 6700
51  is a number whose square is between 50 and 6700
52  is a number whose square is between 50 and 6700
53  is a number whose square is between 50 and 6700
54  is a number whose square is between 50 and 6700
55  is a number whose square is between 50 and 6700
56  is a number whose square is between 50 and 6700
57  is a number whose square is between 50 and 6700
58  is a number whose square is between 50 and 6700
59  is a number whose square is between 50 and 6700
60  is a number whose square is between 50 and 6700
61  is a number whose square is between 50 and 6700
62  is a number whose square is between 50 and 6700
63  is a number whose square is between 50 and 6700
64  is a number whose square is between 50 and 6700
65  is a number whose square is between 50 and 6700
66  is a number whose square is between 50 and 6700
67  is a number whose square is between 50 and 6700
68  is a number whose square is between 50 and 6700
69  is a number whose square is between 50 and 6700
70  is a number whose square is between 50 and 6700
71  is a number whose square is between 50 and 6700
72  is a number whose square is between 50 and 6700
73  is a number whose square is between 50 and 6700
74  is a number whose square is between 50 and 6700
75  is a number whose square is between 50 and 6700
76  is a number whose square is between 50 and 6700
77  is a number whose square is between 50 and 6700
78  is a number whose square is between 50 and 6700
79  is a number whose square is between 50 and 6700
80  is a number whose square is between 50 and 6700
81  is a number whose square is between 50 and 6700